# 配置端口号
server:
  port: 80
# 动态路由配置
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: service-gateway
          uri: lb://service-product
          predicates:
            - Path=/admin/product/**
