# 配置端口号
server:
  port: 80
# 动态路由配置
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: service-product
          uri: lb://service-product
          predicates:
            - Path=/admin/product/**
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/api/user/**
        - id: web-all
          uri: lb://web-all
          predicates:
            - Host=**.gmall.com,gmall.com
