# 配置服务端口号
server:
  port: 10400
canal:
  client:
    instances:
      example:
        host: 192.168.206.120
        port: 11111
spring:
  redis:
    host: 192.168.206.120
    port: 6379
    password: 1234
logging:
  file:
    name: D://gmall/logs/service-canal/info.log