# 配置服务端口号
server:
  port: 10300
spring:
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 192.168.206.120
    port: 6379
    password: 1234
# 线程池参数配置
app:
  threadpool:
    corePoolSize: 4
    maximumPoolSize: 10
    keepAliveTime: 300
    workQueueSize: 60