spring:
  shardingsphere:
    datasource:
      names: master,slave1,slave2
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://192.168.206.120:3306/gmall_product?useSSL=false&characterEncoding=UTF8
        username: root
        password: root
      slave1:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://192.168.206.120:3307/gmall_product?useSSL=false&characterEncoding=UTF8
        username: root
        password: root
      slave2:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.jdbc.Driver
        jdbcUrl: jdbc:mysql://192.168.206.120:3308/gmall_product?useSSL=false&characterEncoding=UTF8
        username: root
        password: root
    rules:
      readwrite-splitting:
        data-sources:
          product-rw-rules:
            type: Static
            props:
              write-data-source-name: master
              read-data-source-names: slave1,slave2
            load-balancer-name: product_lb
        load-balancers:
          product_lb:
            type: ROUND_ROBIN
    props:
      sql-show: true
