# 配置服务端口号
server:
  port: 10100
# 数据库地址信息配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.206.120:3306/gmall_product?useSSL=false&characterEncoding=UTF8
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
  zipkin:
    base-url: http://192.168.206.120:9411
  sleuth:
    sampler:
      probability: 1 # 配置采样率
# mybatis plus相关配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.atguigu.gmall.product.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

app:
  minio:
    endpoint: http://192.168.206.120:9000
    bucketName: gmall
    secretKey: admin123456
    accessKey: admin